# Generated by Django 3.2.5 on 2021-11-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicgirlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacao',
            options={'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.AddField(
            model_name='publicacao',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Publicação'),
        ),
    ]
