# Generated by Django 3.2.5 on 2021-11-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicgirlapp', '0002_auto_20211116_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('editor', '1'), ('editora', '2'), ('Programador', '3'), ('Programadora', '4'), ('Estudante', '5'), ('Autor', '6')], max_length=50, null=True, verbose_name='Cargo do usuario'),
        ),
    ]
