# Generated by Django 3.2.5 on 2021-11-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicgirlapp', '0004_auto_20211116_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rede', models.CharField(choices=[(0, 'Instagram'), (1, 'twitter'), (2, 'Facebook')], max_length=50, verbose_name='Rede social')),
                ('tipo', models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='codigo da rede')),
            ],
        ),
    ]
