# Generated by Django 3.2.5 on 2021-11-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicgirlapp', '0006_redesocial_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='redes',
            field=models.ManyToManyField(to='logicgirlapp.RedeSocial'),
        ),
    ]
