# Generated by Django 3.2.5 on 2021-11-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicgirlapp', '0007_usuario_redes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redesocial',
            name='rede',
            field=models.CharField(choices=[('0', 'Instagram'), ('1', 'twitter'), ('2', 'Facebook')], max_length=50, verbose_name='Rede social'),
        ),
    ]
