# Generated by Django 3.2.5 on 2021-11-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicgirlapp', '0008_alter_redesocial_rede'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='capa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Capa da publicação'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='capa_secao1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Imagem da Seção 2'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='secao1',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='Corpo da Seção 1'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='secao2',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='Corpo da Seção 2'),
        ),
    ]
