# Generated by Django 3.2.5 on 2021-11-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicgirlapp', '0010_auto_20211118_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='referencias',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='Referências'),
        ),
    ]
