# Generated by Django 3.2.5 on 2021-11-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicgirlapp', '0012_usuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Url da Imagem para perfil'),
        ),
    ]
