# Generated by Django 3.2.9 on 2021-11-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicgirlapp', '0014_publicacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='static/publicacoes/', verbose_name='Capa da publicação'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='capa_secao1',
            field=models.ImageField(blank=True, null=True, upload_to='static/publicacoes/', verbose_name='Imagem da Seção 1'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='capa_secao2',
            field=models.ImageField(blank=True, null=True, upload_to='static/publicacoes/', verbose_name='Imagem da Seção 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ImageField(blank=True, null=True, upload_to='static/perfil/', verbose_name='Imagem para o perfil'),
        ),
    ]
