# Generated by Django 3.2.5 on 2021-11-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicgirlapp', '0015_auto_20211119_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='capa',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Capa da publicação'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='capa_secao1',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Imagem da Seção 1'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='capa_secao2',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Imagem da Seção 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Imagem para o perfil'),
        ),
    ]
